import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import "../../extras/ContentTest";
import Link from "next/link";

export default function loginSample({ ContentTest }) {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Account</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <a href="http://localhost:3000">Selections</a>
        </div>
        <main className={styles.main}>
          <p>Our Quality Selections</p>
          <br />
          <p>
            <ContentTest />
          </p>
        </main>
      </div>
    </>
  );
}
